"""Add dim3 and api_key columns to users table

Revision ID: 1d8c021bf3cf
Revises: b0dc408ea698
Create Date: 2025-01-02 20:39:23.891281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8c021bf3cf'
down_revision = 'b0dc408ea698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dim3', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('api_key', sa.String(length=128), nullable=False))
        batch_op.create_unique_constraint(None, ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('api_key')
        batch_op.drop_column('dim3')

    # ### end Alembic commands ###
