"""fastApi migration Initial migration check

Revision ID: c1f049516768
Revises: 1d8c021bf3cf
Create Date: 2025-03-12 18:37:57.775704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1f049516768'
down_revision: Union[str, None] = '1d8c021bf3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_table('user_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('api_key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ai_response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_feedback_pkey')
    )
    # ### end Alembic commands ###
